# Generated by Django 3.0 on 2020-02-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('productDesc', models.TextField()),
                ('productImage', models.FileField(upload_to='static/image')),
                ('productPrice', models.IntegerField()),
            ],
        ),
    ]
