# Generated by Django 3.0 on 2020-02-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='productImage',
            field=models.ImageField(upload_to='static/image'),
        ),
    ]
