# Generated by Django 3.0 on 2020-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200203_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='productImage',
            field=models.ImageField(upload_to='image'),
        ),
    ]
