# Generated by Django 3.0 on 2020-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200203_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='productImage',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
